all:
  hosts:
    master-1:
      ansible_host: 158.160.123.207
      ip: 10.0.1.30
      access_ip: 10.0.1.30
      ansible_user: debian
    worker-1:
      ansible_host: 130.193.36.171
      ip: 10.0.1.32
      access_ip: 10.0.1.32
      ansible_user: debian
    worker-2:
      ansible_host: 89.169.141.192
      ip: 10.0.1.22
      access_ip: 10.0.1.22
      ansible_user: debian
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}